FROM registry.risc-vers.cn/wg-cloudcomputing/openeuler:24.03-lts

ARG ARCH
ARG SONOBUOY_ARCH
ARG BAZEL_ARCH

ENV BAZEL_VERSION=5.4.1
ENV GIMME_GO_VERSION=1.22.8
ENV GIMME_DOWNLOAD_BASE=https://mirrors.aliyun.com/golang
ENV OPERATOR_COURIER_VERSION=2.1.11
ENV SONOBUOY_VERSION=0.56.9
ENV GOLANGCI_LINT_VERSION=v1.60.1

ENV KUBEVIRT_CREATE_BAZELRCS=false
ENV DEBIAN_FRONTEND=noninteractive

# Install packages

RUN yum install -y \
         java-11-openjdk-devel \
        libvirt-devel \
        cpio \
        patch \
        make \
        git \
        sudo \
        gcc \
        gcc-c++ \
        glibc-static \
        glibc-devel \
        libstdc++-static \
        findutils \
        rsync \
        qemu-img \
        protobuf-compiler \
        python3 \
        python3-devel \
        python3-pip \
        python3-setuptools \
        rpm \
        jq \
        wget \
        rubygems \
        diffutils  \
        curl  \
        skopeo \
        zstd \
        xz \
        diffutils && \
      yum clean all -y

# Avoids the need to install sssd-client by disabling lookups
COPY nsswitch.conf /etc/nsswitch.conf

# Necessary for generation of HTML-formatted API docs (.adoc)
RUN gem install asciidoctor

# Generates Asciidoc files from swagger.json
ADD https://storage.googleapis.com/builddeps/swagger2markup-cli-1.3.3.jar /opt/swagger2markup-cli/swagger2markup-cli-1.3.3.jar

# Necessary for Bazel to find Python inside the container
#
# https://github.com/bazelbuild/bazel/issues/8665
# https://github.com/bazelbuild/bazel/issues/11554
RUN ln -s /usr/bin/python3 /usr/bin/python

ENV PATH=$JAVA_HOME/bin:$PATH
# reference to master is for an external repo and can't yet be changed
RUN mkdir -p /gimme &&  curl -L \
    https://github.com/travis-ci/gimme/raw/refs/heads/master/gimme | \
    HOME=/gimme bash >> /etc/profile.d/gimme.sh

ENV GOPATH="/go" GOBIN="/usr/bin"  GO111MODULE="on" GOPROXY=https://goproxy.cn
RUN set -x && \
    mkdir -p /go && \
    source /etc/profile.d/gimme.sh && \
    go install -v golang.org/x/tools/cmd/goimports@d5fe738 && \
    go install -v mvdan.cc/sh/v3/cmd/shfmt@v3.1.1 && \
    go install -v k8s.io/code-generator/cmd/conversion-gen@v0.31.1  && \
    go install -v k8s.io/code-generator/cmd/deepcopy-gen@v0.31.1 && \
    go install -v k8s.io/code-generator/cmd/defaulter-gen@v0.31.1  && \
    go install -v k8s.io/kube-openapi/cmd/openapi-gen@f7e401e && \
    go install -v github.com/golang/protobuf/protoc-gen-go@1643683 && \
    go install -v k8s.io/code-generator/cmd/client-gen@v0.31.1 && \
    go install -v github.com/securego/gosec/v2/cmd/gosec@0ce48a5 && \
    go install -v sigs.k8s.io/controller-tools/cmd/controller-gen@v0.16.3 && \
    go install -v github.com/kubevirt/monitoring/monitoringlinter/cmd/monitoringlinter@e2be790 && \
    go clean -cache -modcache

RUN /bin/bash -c "set -x && \
    source /etc/profile.d/gimme.sh && \
    go install -v github.com/mattn/goveralls@21feffdfd && \
    go install -v github.com/rmohr/mock/mockgen@v0.0.0-20170327080805-5980f5d9a70d && \
    go install -v github.com/rmohr/go-swagger-utils/swagger-doc@v0.0.0-20181110145135-878f7deb1d17 && \
    go clean -cache -modcache"
RUN git clone https://github.com/kubernetes/test-infra.git &&\
    cd /test-infra && \
    git checkout f2693aba912dd40c974304caca999d45ee8dce33
RUN set -x && \
    source /etc/profile.d/gimme.sh && \
    cd /test-infra/robots/pr-creator && \
    go install && \
    cd /test-infra/robots/issue-creator && \
    go install && \
    cd /test-infra/robots/pr-labeler && \
    go install && \
    go clean -cache -modcache -r && \
    rm -rf /test-infra && \
    rm -rf /go && mkdir /go

RUN set -x && \
    source /etc/profile.d/gimme.sh && \
    go install -v mvdan.cc/gofumpt@v0.6.0 && \
    go install github.com/golangci/golangci-lint/cmd/golangci-lint@$GOLANGCI_LINT_VERSION

RUN pip3 install --upgrade operator-courier==${OPERATOR_COURIER_VERSION}

RUN set -x && \
    wget https://code.openruyi.cn/-/project/10984/uploads/fdeb0bc9b0a0de465bb12980c7f64e48/sonobuoy_v0.56.9_linux_riscv64.tar.gz && \
    tar xvf sonobuoy_v${SONOBUOY_VERSION}_linux_${SONOBUOY_ARCH}.tar.gz && \
    chmod +x sonobuoy && \
    mv sonobuoy /usr/bin && \
    rm sonobuoy_v${SONOBUOY_VERSION}_linux_${SONOBUOY_ARCH}.tar.gz

COPY rsyncd.conf /etc/rsyncd.conf

COPY entrypoint.sh /entrypoint.sh

COPY create_bazel_cache_rcs.sh /create_bazel_cache_rcs.sh

RUN if test "${ARCH}" = "riscv64"; then \
       wget https://code.openruyi.cn/-/project/10983/uploads/51ef2fdff61860d3571c3a1d8188880c/bazel-6.5.0-linux-riscv64.tar.gz && \
       tar -xzf bazel-${BAZEL_VERSION}-linux-${BAZEL_ARCH}.tar.gz && \
       cp bazel-${BAZEL_VERSION}-${BAZEL_ARCH}/bin/bazel-${BAZEL_VERSION}-${BAZEL_ARCH} /usr/bin/bazel && \
       chmod u+x -R /usr/bin/bazel; \
    fi

# Add /root/go/src/kubevirt.io/kubevirt and mark it as a safe directory for git
RUN mkdir -p /root/go/src/kubevirt.io/kubevirt && git config --global --add safe.directory /root/go/src/kubevirt.io/kubevirt
ENTRYPOINT [ "/entrypoint.sh" ]
